# .github/workflows/weekly_pulse.yml
name: Generate Weekly Pulse

on:
  schedule:
    # Runs at 05:00 UTC every Sunday.
    - cron: '0 5 * * 0'
  workflow_dispatch:
    # Allows manual running from the Actions tab

jobs:
  generate-weekly-summary:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate Weekly Pulse
        run: python generate_weekly_pulse.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}